services:
  nginx:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - webapi

  webapi:
    build:
      context: ./backend
      dockerfile: ledger12.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__AppDbContextConnection=Data Source=/data/ledger12.db
    volumes:
      - sqlitedata:/data

  migration-job:
    build:
      context: ./backend
      dockerfile: ledger12.MigrateFromLedger11/Dockerfile
    profiles:
      - migration
    environment:
      - ConnectionStrings__AppDbContextConnection=Data Source=/data/ledger12.db
    volumes:
      - sqlitedata:/data
      - ./ledger11data:/ledger11data
    restart: no

volumes:
  sqlitedata: