services:
  cloudflaretunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$L12_TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    depends_on:
      - webapi

  webapi:
    build:
      context: ./backend
      dockerfile: ledger12.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__AppDbContextConnection=Data Source=/data/ledger12.db
    volumes:
      - ledger12data:/data

  migration:
    build:
      context: ./backend
      dockerfile: ledger12.MigrateFromLedger11/Dockerfile
    profiles:
      - migration
    environment:
      - ConnectionStrings__AppDbContextConnection=Data Source=/data/ledger12.db
    volumes:
      - ledger12data:/data
      - ./backend/ledger11data:/ledger11data
    restart: no

volumes:
  ledger12data:
    external: true