import {
  ShoppingCart,
  Home,
  Plug,
  Car,
  Shield,
  Utensils,
  Film,
  Heart,
  Smile,
  CreditCard,
  Shirt,
  Gift,
  Plane,
  Book,
  PiggyBank,
  Bell,
  Calendar,
  Camera,
  CheckCircle,
  Clipboard,
  Clock,
  Edit,
  Eye,
  File,
  Folder,
  Globe,
  Info,
  Link,
  Loader,
  Lock,
  Mail,
  MessageCircle,
  Search,
  Laptop,
  Monitor,
  Smartphone,
  Wallet,
  Hammer,
  Briefcase,
  Package,
  Tag,
  MoreHorizontal,
  type LucideIcon,
  DumbbellIcon,
  VolleyballIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  // Original icons
  "shopping-cart": ShoppingCart,
  home: Home,
  plug: Plug,
  car: Car,
  shield: Shield,
  utensils: Utensils,
  film: Film,
  heart: Heart,
  smile: Smile,
  "credit-card": CreditCard,
  shirt: Shirt,
  gift: Gift,
  plane: Plane,
  book: Book,
  "piggy-bank": PiggyBank,
  "dots-horizontal": MoreHorizontal,

  // Popular utility icons
  bell: Bell,
  calendar: Calendar,
  camera: Camera,
  "check-circle": CheckCircle,
  clipboard: Clipboard,
  clock: Clock,
  edit: Edit,
  eye: Eye,
  file: File,
  folder: Folder,
  globe: Globe,
  info: Info,
  link: Link,
  loader: Loader,
  lock: Lock,
  mail: Mail,
  "message-circle": MessageCircle,
  search: Search,

  // Object-oriented icons
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  wallet: Wallet,
  hammer: Hammer,
  briefcase: Briefcase,
  package: Package,
  tag: Tag,

  // Sports and fitness icons
  dumbbell: DumbbellIcon,
  volleyball: VolleyballIcon,
};

export const getIcon = (iconName?: string): LucideIcon => {
  if (!iconName) return MoreHorizontal;

  const icon = iconMap[iconName] || MoreHorizontal;
  return icon;
};
